### ISSUE TITLE
Issue with conversion from PAR to absPAR

### ISSUE THREAD

**Issue by lilydun1** [lilydun1/Honours#1]
Having issues converting PAR (m-2 s-1) to absPAR (tree-1 day-1). My equation output is not matching MAESPA outputs 
- My equation is within the function __PAR_calculator_ft__ (line 75) in script __Function_M__ in the project __models__. 
- I used the [paper](https://seer.sct.embrapa.br/index.php/agrometeoros/article/view/26527) for the conversion equations. 
- eqn 38 within the paper for PAR (µmol m-2 s-1) to Rs (W m-2) conversion. 
- eqn 12 within the paper for (W m-2) to (MJ m-2 time-1) conversion. 

Tried to set up a simulation to match my output to MAESPA 
- Thought it could have been due to self-shading yet I ran MAESPA with the exact same conditions with one tree in the stand and a leaf area of 0.1 m^2 and still not getting the same result from my function. 

Outputs from the 0.1 leaf area stand
- MAESPA  absPAR = 0.5614
- Mine absPAR = 1.64226
Also tried with 0.5 
- MAESPA  absPAR = 2.7943
- Mine absPAR = 8.211299

To see how I ran mine 
- See line 94 in script Function_M
- The __try__ folder within the __simulations__ folder in the project __models__ is me running the lone tree simulation.

**Comment by dfalster** [comment]
Hi Lily, I wonder if you unit conversions are correct. I checked in Maespa and found this constant, that is used throughout the code -- converts from `umol quanta` to `J`. 

![image](https://user-images.githubusercontent.com/3589590/132181838-fcd21f8c-7f1d-4413-b16c-d6f6da20ed7a.jpeg)

https://bitbucket.org/remkoduursma/maespa/src/0cb01e8149f64bd2122831a41d73f97f4e08a34d/maestcom.f90#lines-30

Using this I get a much better result:

```
library(tidyverse)
library(maeswrap)

# conatnt to converts ymol/s to M J / h
UMOLperStoMJperH <-
  3600 /  # s / hr
  4.57 /  # umol quanta / J
  10^6    # J / MJ
# load met and convert PAR to J/hr
met <- 
    readmet(filename = "met.dat", nlines = -1) %>% 
    as_tibble() %>% 
    select(time = TIME, PAR) %>%
    mutate(      
      MJ_per_H = PAR  * UMOLperStoMJperH  # MJ
      )

  # integrate over the day using trapezoidal integration
  pracma::trapz(met$time, met$MJ_per_H)
```
This gives 7.26 MJ/m2/day

Multiplying by 0.1ms gives 0.726 MJ/ tree / day for absPAR

By comparison MAESPA absPAR  gives 0.5614

It makes sense that our value is slightly higher as we haven't taken account of leaf inclination (calculations above assume leaves are horizontal)

What leaf inclination is being used in your simulation? We need to calculate an extinction coefficient from this.

**Comment by lilydun1** [comment]
Ooo interesting, this is the bit about leaf inclination from the MAESPA manual:

> This namelist describes the leaf angle distribution, used in the radiative transfer calculations. There are three options to specify this namelist:
> __(a)__ AVGANG > 0 
The mean leaf inclination angle is specified by AVGANG. If NALPHA = 1, there is just on leaf angle class with angle AVGANG. If NALPHA > 1, AVGANG is used to generate the LIA distribution assuming an elliptical distribution.
> __(b)__ ELP > 0.0 
ELP is the parameter of an ellipsoidal leaf angle distribution: it represents the ratio of the horizontal and vertical axes of an ellipsoid. If ELP = 1, the distribution is spherical; if ELP = 0.5, the distribution is erectophile; and if ELP = 2, the distribution is planophile. If NALPHA = 1: there is just one leaf angle class, and the average leaf angle is given by AVGANG or AVGANG(ELP). If NALPHA > 1 (max 9): there are NALPHA leaf angle classes, and the distribution of angles is elliptical with parameter ELP.
> __(c)__ ELP < 0.0 
The proportion of leaf area in each angle class is read in from array FALPHA. The number of angle classes is given by NALPHA (max 9).

And mine is set up to be 
AVGANG = 77 
NALPHA = 5 
ELP = 1

What should be the next step?

**Comment by dfalster** [comment]
Is the angle -- angle from vertical, or angle from horizontal? 

What is the distribution that results from the above info you provided?

**Comment by dfalster** [comment]
Some background on extinction coefficients is available here: 

- https://www.sciencedirect.com/science/article/pii/0168192386900109 (proposed the ellipsoidal distribution used in maetra)
- http://doi.org/10.1016/j.agrformet.2006.12.003 compares a bunch of leaf angle distributions


A rough calculation on extinction coeff is`cos(theta) * cos(zenith)`, where theta is the angle of leave from the horizontal, zenith is angle of the sun from vertical (this is suitable for leaves somewhat flat, sun up in the sky. 

Above the maespa estimate of light to ours was  0.5614/0.726 = 0.7732782. You get this value of extinction coefficient with flat leaves and sun at 40deg in sky, or leaves at 20deg from horizontal and sun at 35 deg in sky. 

I'd suggest moving forward with an extinction coefficient of 0.77 for now.

**Comment by lilydun1** [comment]
Overall getting a bit confused, added the 0.77 extinction coefficient, still getting different results from maespa. When the focal tree is shorter than the stand my result is smaller than maespas but when the   focal tree is taller mine is larger than maespas 

```
# conatnt to converts ymol/s to M J / h
UMOLperStoMJperH <-
  3600 /  # s / hr
  4.57 /  # umol quanta / J
  10^6    # J / MJ
#getting the LAI above the focal tree
data = results_f[["H15_V0.1_L4.402_F0.75_S3"]]
L_ft = data %>% 
    filter(focal == "TRUE") %>% 
    pull(lai) 
# load met and convert PAR to J/hr
met <- 
  readmet(filename = "met.dat", nlines = -1) %>% 
  as_tibble() %>% 
  select(time = TIME, PAR) %>%
  mutate(      
    PAR = PAR * exp(-0.77*L_ft),
    MJ_per_H = PAR  * UMOLperStoMJperH  # MJ
    )
# integrate over the day using trapezoidal integration
pracma::trapz(met$time, met$MJ_per_H)*47.62
```
mine = 11.13593
maespa = 58.5545

also found this in the manual, unsure what it means though 
>Number of layers and angles to integrate over
>NOLAY is the number of layers in the crown assumed when calculating radiation interception. PPLAY is the number of points per layer (this must be divisble by 4, if it is not the closest smaller number divisible by 4 is used). The maximum number of layers is given in maestcom.f90 as MAXLAY. Default: 6.
>NZEN is the number of zenith angles for which diffuse transmittances are calculated; NAZ is the number of azimuth angles for which the calculation is done.

mine is set at 
nolay = 6
nzen = 5
naz= 11

I'm wondering if the radiation is direct or diffuse is affecting the result?

**Comment by dfalster** [comment]
First, k (extinction coefficient comes in in two ways. the code above should be `PAR = 0.77* PAR * exp(-0.77*L_ft)`

The second 0.77 accounts for reduction via shading. The first accounts for amount your leaves intercept of incoming light. So adding 0.77 should decrease PAR intercepted, which should bring the values when local tree is closer closer to maespa. 

Second, can you confirm where the lai value you're using is coming from? 

Indeed, Maespa uses a two stream approach, so we may need to change that. 

Also, can you create a plot with results from the version above plotted over the maespa results, for one of your results panels, e.g. LAi =5.3XX, v = 0.1?

**Comment by dfalster** [comment]
Another suggestion is to export hourly (or finer) results in the `try` simulation. Belinda says PAR in these come out in ymol/m2/s. So will be helpful point of comparison.

**Comment by lilydun1** [comment]
The lai value comes from this function:
```
model_simp_f <- function(data) {
  df <- data %>% 
    mutate(t_h = htcrown + httrunk) %>% 
    arrange(desc(t_h)) %>% 
    group_by(t_h, focal) %>% 
    summarise(larea = sum(larea)) %>% 
    ungroup() %>% 
    arrange(desc(t_h)) %>% 
    mutate(
      lai = cumsum(larea)/10204, 
      light_ft = exp(-0.5*lai),
      lai_ppa = floor(lai),
      light_ppa = exp(-0.5*lai_ppa)) %>% 
    as_tibble()
}
```
so it's the cumulative LAI over the focal tree, which of course changes as the focal height changes. 

Here is the plot with updated conversion and extinction coefficient:
![Rplot](https://user-images.githubusercontent.com/89431483/132291245-040883b0-c76e-4dfa-91a4-1ce4265b39e6.png)

**Comment by dfalster** [comment]
Can you push latest code too?

**Comment by lilydun1** [comment]
Yep! just did, its a bit of a mess at the moment

**Comment by dfalster** [comment]
Hi Lily,So the difference in light at high light is most likely the self shading effect. Do you have an idea on how we could separate this? 

Could you run a series of new simulations with 

- surrounding stand of LAI = 3, V=0.1
- focal height ranging from 0-2 (as current)
- change the leaf area of the focal tree from 0.1 to 47m2, e.g. 0.1, 0.5, 1, 10, 50m2? This will enable us to look at the interaction of height and self shading. 

Make sense?

Maybe first spend some time consolidating existing code?

**Comment by lilydun1** [comment]
oh yeah, sounds like that could work. Yeah really need to tidy up my code, I have an assessment centre for a job tomorrow, so won't be able to do any work yet should get onto it on Thursday.
